name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
  earthly:
    runs-on: ubuntu-latest
    container: earthly/earthly:v0.8.5
    steps:
      - run: earthly bootstrap
      - name: Listing files
        run: |
          ls -la
          cd ..
          ls -la
          cd ./cli-test-case
          ls -la
      - name: Check for docker-compose file
        run: (ls /docker-compose && echo Found docker-compose) || (echo No docker-compose)
      - name: Docker in Docker
        run: earthly --ci --push -P +ci


