name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
  earthly:
    runs-on: ubuntu-latest
    container: earthly/earthly:v0.8.5
    steps:
      - run: earthly bootstrap
      - uses: action/checkout@v3
      - name: Check for Earthfile file
        run: (ls Earthfile && echo Found Earthfile) || (echo No Earthfile)
      - name: Docker in Docker
        run: earthly --ci --push -P +ci