name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
  earthly:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest" # or pin to an specific version, e.g. "0.8.1"
      - uses: actions/checkout@v2
      - name: what version is installed?
        run: earthly --version
      - name: run the earthly hello world
        run: earthly github.com/earthly/hello-world:main+hello
      - run: earthly bootstrap
      - uses: actions/checkout@v3
      - name: Check for Earthfile file
        run: (ls Earthfile && echo Found Earthfile) || (echo No Earthfile)
      - name: earthly 
        run: earthly --ci --push -P +ci
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: "**/*.html"