name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  # checkout:
  #   name: Checkout
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
      
  earthly:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest" # or pin to an specific version, e.g. "0.8.1"
      - uses: actions/checkout@v2
      - run:  echo "boot=$(earthly bootstrap)\n" >> $GITHUB_OUTPUT
        id: bootstrap
      - uses: actions/checkout@v3
      - name: Check for Earthfile file
        run: (ls Earthfile && echo Found Earthfile) || (echo No Earthfile)
        id: check

      - name: Run Earthly and capture output
        id: earthly
        run: earthly --ci --output --push -P +ci
      - run: ls -la
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git gcc make libssl-dev pkg-config

      - name: Install Rust and Cargo
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Clone and build htmlq
        run: |
          git clone https://github.com/mgdm/htmlq.git
          cd htmlq
          cargo build --release
          sudo cp target/release/htmlq /usr/local/bin/

      - name: Run htmlq 
        run: |
          COVERAGE=$(htmlq 'tr:last-child td:last-child' -t coverage_result.html)

      - name: Save Coverage to GitHub Actions output
        id: save_coverage
        run: echo "total_coverage=$COVERAGE \n" >> $GITHUB_OUTPUT

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ steps.save_coverage.outputs.total_coverage }}
          regex: '\(statements\)(?:\s+)?(\d+(?:\.\d+)?%)'

      - name: Coverage badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: coverage
          ICON: 'https://badgen.net/codecov/c/gitlab/gitlab-org/gitaly'
          STATUS: ${{ steps.regex-match.outputs.match }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      # - name: check test coverage
      #   uses: vladopajic/go-test-coverage@v2
      #   with:
    
          
      #     # Configure action by specifying input parameters individually (option 2).
      #     # If you are using config file (option 1) you shouldn't use these parameters, however
      #     # specifing these action parameters will override appropriate config values.
      #     profile: coverage_result.html
      #     local-prefix: github.com/LittleRed945/cli-test-case
      #     threshold-file: 80
      #     threshold-package: 80
      #     threshold-total: 95