name: Earthly Test
run-name: ${{ github.actor }} is testing 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  earthly_test:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.14
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - run:  earthly bootstrap
      - name: Check for Earthfile file
        run: (ls Earthfile && echo Found Earthfile) || (echo No Earthfile)
        id: check

      - name: Run Earthly and capture output
        id: earthly
        run: |
          output=$(earthly --ci --push -P +ci 2>&1)
          echo "$output"
          coverage=$(echo "$output" | grep "total:" | sed 's/.*)\s*//')
          echo "coverage=$coverage" >> $GITHUB_OUTPUT

      - name: Update README.md with coverage badge
        env:
          COVERAGE_PERCENTAGE: ${{ steps.earthly.outputs.coverage }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Generate new badge URL
          BADGE_URL="https://img.shields.io/badge/coverage-${COVERAGE_PERCENTAGE}%25-brightgreen"

          # Fetch the current README.md content
          README_CONTENT=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3.raw" \
            -s https://raw.githubusercontent.com/${{ github.repository }}/main/README.md)

          # Update README.md content
          UPDATED_README_CONTENT=$(echo "$README_CONTENT" | sed "s|!\[Coverage\](https://img.shields.io/badge/coverage-[0-9]*%25-brightgreen)|![Coverage]($BADGE_URL)|")

          # Commit and push the updated README.md
          echo "$UPDATED_README_CONTENT" > README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit --amend --no-edit 
          git push origin master